version: "3.7"
services:
  code-server:
    build: .
    container_name: code-server
    environment:
      - DOCKER_USER=teste
      - PASSWORD=teste # Substitua isto pela sua senha de login
    volumes:
      - ./config:/config
      - $PWD:/home/coder/workspace
    ports:
      - "8080:8080"
      - "2222:22"
    restart: unless-stopped
    networks:
      - code-server

networks:
  code-server: